name: pin_biometric_offline
description: A minimal Flutter app demonstrating offline PIN + biometric authentication.
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  local_auth: ^2.2.0
  flutter_secure_storage: ^10.0.0
  crypto: ^3.0.2
  camera: ^0.10.5
  image_picker: ^1.0.4
  google_mlkit_pose_detection: ^0.10.0
  google_mlkit_face_detection: ^0.9.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - 'assets/Screenshot 2025-11-28 103159.jpg'
